# Generated by Django 4.0.1 on 2022-01-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_listing_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='Data',
        ),
    ]
