# Generated by Django 4.0.1 on 2022-01-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_connections_rename_listing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='importance',
            field=models.IntegerField(default=2, max_length=2),
        ),
    ]
