# Generated by Django 4.0.1 on 2022-01-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_networkevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkevents',
            name='importance',
            field=models.IntegerField(default=2, max_length=2),
        ),
    ]
