# Generated by Django 4.0.1 on 2022-02-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_alter_data_desc_alter_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
